disabled_rules:
    - line_length
    - trailing_whitespace
    - type_body_length
    - file_length
    - object_literal
excluded:
    - Pods
opt_in_rules:
    - empty_count
    - explicit_init
    - closure_spacing
    - overridden_super_call
    - redundant_nil_coalescing
    - private_outlet
    - nimble_operator
    - attributes
    - operator_usage_whitespace
    - closure_end_indentation
    - first_where
    - sorted_imports
    - object_literal
    - number_separator
    - prohibited_super_call
    - fatal_error_message
identifier_name:
    excluded:
        - id
line_length: 120
number_separator:
    minimum_length: 5
custom_rules:
    no_print:
        included: ".*.swift"
        name: "No calls to print(...)"
        regex: 'print\([^)]+\)'
        match_kinds:
            - identifier
            - string
            - string_interpolation_anchor
        message: "You should not use print(...) in production."
        severity: warning
